version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: devnology_db
    restart: always
    environment:
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: root
      POSTGRES_DB: whitelabel
    ports:
      - "4002:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: